### ISSUE TITLE
[FEATURE] common vs official name (South Korea vs Republic of Korea)

### ISSUE THREAD

**Issue by MathiasWinckel** [RosaeNLG/rosaenlg#100]
**Is your feature request related to a problem? Please describe.**

Using the countries lib, I would use a more formal version "Republic of Korea" instead of the common "South Korea"

**Describe the solution you'd like**
I saw you have this version named "official" in _node_modules\world-countries\countries.json_ but it seems you extract some of its content for the english or french resource and doesn't keep the "official" attribute.

Could be interesting to keep it, and maybe add a possible _OFFICIAL_COUNTRY_NAME_ _"form"_ option in the _"country"_ template?

**Describe alternatives you've considered**

I was thinking of modifying the resource during runtime. 
Or wrapping the country pug template call to catch the call on South Korea.
But a native option to use it would be better.

**Comment by ludans** [comment]
Yes it just keeps the common name for the `world-countries` external lib.
We would keep both and make it available in the mixin.

I would be happy to review and validate a PR on this :)

In the `rosaenlg-country` module:
- extract the data in `gulpfile.js`
- make it available through the mixin (add some flag for instance)
- for EN and FR
- add some tests
- update the doc

PS: Please be aware that official name for Macau (or Macao) is: "Macao Special Administrative Region of the People's Republic of China".

**Comment by ludans** [comment]
@MathiasWinckel are you willing to make the change? Otherwise I shall close the ticket.

**Comment by ludans** [comment]
See #133 . Will be added in the next release.
