### ISSUE TITLE
[FEATURE] a basic "first" drawing mode for synonyms

### ISSUE THREAD

**Issue by MathiasWinckel** [RosaeNLG/rosaenlg#101]
**Is your feature request related to a problem? Please describe.**

When starting a project, I find a very basic and simple draw mode for synonyms to be helpful.

**Describe the solution you'd like**

A "first" synonym drawing method, which simply draw the first synonym, but still try to draw the next one when the first synonym is an empty text.
I already made a first implementation in my local _SynManager_, using what was done for the already existing modes.

**Describe alternatives you've considered**

Maybe the random mode, using a specific seed, could be manipulated to do this... 

**Additional context**

It's a really basic approach, and as I said, I mostly use it in an early stage of development to start working on the other aspects of the project before dealing with the variants.

Of course, it gives a very bad coverage in regard of testing, and at some point I definitely switch on a more complex mode. 
But even after a while, it may be easier to start dealing with an issue with something like that, when debugging, you don't really have to try too hard to understand which synonyms was triggered and why. 
And I can deal with the synonym part once I'm satisfied with the basic "first" draw method.

I thought it could be interesting to share this approach, and maybe enrich the _SynManager_ with this mode.

**Comment by ludans** [comment]
You can do it **locally** using `synz {force:1}`. It will always trigger the first synonym, unless it is empty.
This is useful while developing - well, this is the way *I* do develop.

If I understand well, you would wish a global parameter to do that, in `defaultSynoMode` (e.g. `forceFirst` or `force_1`), when developing, and at some point when developing changing that global parameter. Is that right?

Why not - I think I can accept a PR on that! As you mention it all happens in `SynManager.ts`.
