### ISSUE TITLE
[FEATURE] additional mode for synonyms

### ISSUE THREAD

**Issue by blegaut** [RosaeNLG/rosaenlg#106]
**Is your feature request related to a problem? Please describe.**
I am repeatedly (in various paragraphs of a text) using a mixin containing synonyms. However, some of them are very similar by the vocabulary or grammatical structure.

```
mixin preferences()
  synz {mode: 'once'}
    syn 
        | comme vous le souhaitez
    syn
        | comme vous le préférez 
    syn
        | en accord avec votre souhait 
    syn
        | en accord avec votre préférence          
    syn
        | comme demandé
    syn
        |. c'est ce que vous souhaitiez !
        
p
  | #[+preferences] 
  | #[+preferences]
  | #[+preferences]
  | #[+preferences]
  | #[+preferences]  
```

I would like to make sure that when writing a new synonym,  a synonym, not too closed to the previous one, is chosen. For example, I want to avoid writing these two sequences:

- `comme vous le souhaitez , comme vous le préférez `
- `comme vous le souhaitez , en accord avec votre souhait `

**Describe the solution you'd like**

For my understanding, the choosebest approach doesn't really help here since it would need to evaluate the whole text, which would impact performance and would be overkill.

A great solution would be a new option, maybe called  'once with diversity', that would do the following  when calling the mixin
- create the Possible_Synonyms list by including all the non yet written synonyms
- evaluate the "distance" between the last written synonym and the element of the Possible_Synonyms list
- remove from the  Possible_Synonyms list the synonyms which are too close to the last written synonym
- draw the synonym to eb written from the  Possible_Synonyms list

I am not sure what would be the best algorithm to evaluate the distance. Maybe the choosebest approach could be reused.

**Describe alternatives you've considered**
As an ugly hack, I have implemented the following:

```
mixin preferences()
  synz {mode: 'once'}
    syn
      if getValue('PREFERENCE_1') !=='COMME' && getValue('PREFERENCE_2') !=='SOUHAIT'
        | comme vous le souhaitez
        - recordValue('PREFERENCE_1','COMME')
        - recordValue('PREFERENCE_2','SOUHAIT')
    syn
      if getValue('PREFERENCE_1') !=='COMME' && getValue('PREFERENCE_2') !=='PREFERENCE'
        | comme vous le préférez 
        - recordValue('PREFERENCE_1','COMME')   
        - recordValue('PREFERENCE_2','PREFERENCE')  
    syn
      if getValue('PREFERENCE_1') !=='EN_ACCORD' && getValue('PREFERENCE_2') !=='SOUHAIT'
        |  en accord avec votre souhait 
        - recordValue('PREFERENCE_1','EN_ACCORD')
        - recordValue('PREFERENCE_2','SOUHAIT')
    syn
      if getValue('PREFERENCE_1') !=='EN_ACCORD' && getValue('PREFERENCE_2') !=='PREFERENCE'
        | en accord avec votre préférence 
        - recordValue('PREFERENCE_1','EN_ACCORD') 
        - recordValue('PREFERENCE_2','PREFERENCE')            
    syn
      if getValue('PREFERENCE_1') !=='DEMANDE'
        | comme demandé
        - recordValue('PREFERENCE_1','DEMANDE') 
    syn
      if getValue('PREFERENCE_2') !=='SOUHAIT'
        | . c'est ce que vous souhaitiez !
        - recordValue('PREFERENCE_2','SOUHAIT')
        
p
  | #[+preferences] 
  | #[+preferences]
  | #[+preferences]
  | #[+preferences]
  | #[+preferences]  
```

**Additional context**
Add any other context about the feature request here.

**Comment by ludans** [comment]
`choosebest` computes only the part of the text it is selected on.
For your very specific example it would be ideal. Yet I think that these texts are introductions, and that you have other pieces of text between these introductions. This will mislead `choosebest` - and you have to find another approach.

I suggest 2 simple to implement options:

1/ Use` {mode:'sequence'}`, and alternate synonyms wisely in your structure.

i.e.
```
comme vous le souhaitez
en accord avec votre préférence
comme demandé
en accord avec votre souhait
comme vous le préférez
```

(and typically not
```
comme demandé
comme vous le préférez
comme vous le souhaitez
en accord avec votre souhait
en accord avec votre préférence
```
)

This is simple to implement and to maintain.

2/ Organize your synonyms in categories. This will force to alternate.

```
mixin synSouhait
  synz {mode: 'once'}
    syn 
        | comme vous le souhaitez
    syn
        | en accord avec votre souhait 
    syn
        |. c'est ce que vous souhaitiez !

mixin synPref
  synz {mode: 'once'}
    syn
        | comme vous le préférez 
    syn
        | en accord avec votre préférence          

mixin synBoth
  synz {mode: 'once'}
	syn
		| #[+synSouhait]
	syn
		| #[+synPref]

```

This also works, generates more diversity, and remains quite simple to maintain.

**Comment by blegaut** [comment]
Thank you Ludan

I am afraid that your two options are not satisfactory enough :
The first one lacks diversity as you mentioned
The second one doesn't prevent undesirable sequence such as: 
- comme vous le souhaitez , comme vous le préférez
- en accord avec votre souhait, en accord avec votre préférence    

I believe that I will stick with my ugly hack for now. Maybe I'll propose you a better option later.

**Comment by ludans** [comment]
Thanks for your feedback.
Actually alternative 2 should work but does not. There might be a bug in `once` mode. I opened #110 and will investigate.
