### ISSUE TITLE
[FEATURE] better handling of conjugated verbs in stemming

### ISSUE THREAD

**Issue by blegaut** [RosaeNLG/rosaenlg#107]
**Is your feature request related to a problem? Please describe.**
I tried to use the choosebest  synonym functionality, but it seems that the stemming is not good enough with French conjugaison

```
- var param = {debug:true, among:100}
p
  choosebest param
    synz
      syn
        | souhait souhaitons
      syn
        | souhait préférons

  | !{JSON.stringify(param.debugRes)}
```
The above code might produce.

`<p>Souhait souhaitons { "maxTest": 100, "perfectScoreAfter": 0, "bestScore": 0, "bestText": "souhait souhaitons", "bestDebug": { "filteredAlt": [ "souhait", "souhaiton" ], "identicals": null, "identicalsMap": {}, "wordsWithPos": {}, "score": 0}, "worstScore": 0, "worstText": "souhait souhaitons", "worstDebug": { "filteredAlt": [ "souhait", "souhaiton" ], "identicals": null, "identicalsMap": {}, "wordsWithPos": {}, "score": 0}}</p>`

**Describe the solution you'd like**
I hope that we could find a proper stemming for the conjugated verb in French, maybe by 
1) converting the verb into its infinitive
2) using the stemming based on the infinitive

or using a better stemmer

**Describe alternatives you've considered**
An alternative solution is to use the` identicals option`

```
- var param = {debug:true, among:100,identicals: [ ['souhait', 'souhaitons']]}
p
  choosebest param 
    synz
      syn
        | souhait souhaitons
      syn
        | souhait préférons

  | !{JSON.stringify(param.debugRes)}
```

**Additional context**
Add any other context about the feature request here.

**Comment by ludans** [comment]
Your analysis is good: this comes from the French stemmer.

RosaeNLG uses `synonym-optimizer` package (which I wrote). `synonym-optimizer` manages stop words and stemming.
French stemming is done using `snowball-stemmer.jsx`. It uses snowball algorithm, which is supposed to be a reference.

https://www.npmjs.com/package/snowball-stemmer.jsx

I believe it uses this code:
https://github.com/shibukawa/snowball/blob/master/snowball/algorithms/french/stem_ISO_8859_1.sbl

```
    define verb_suffix as setlimit tomark pV for (
        [substring] among (
            'ions'
                (R2 delete)

            '{e'}' '{e'}e' '{e'}es' '{e'}s' '{e`}rent' 'er' 'era' 'erai'
            'eraIent' 'erais' 'erait' 'eras' 'erez' 'eriez' 'erions'
            'erons' 'eront' 'ez' 'iez'

            // 'ons' //-best omitted

                (delete)

            '{a^}mes' '{a^}t' '{a^}tes' 'a' 'ai' 'aIent' 'ais' 'ait' 'ant'
            'ante' 'antes' 'ants' 'as' 'asse' 'assent' 'asses' 'assiez'
            'assions'
                (delete
                 try(['e'] delete)
                )
        )
    )
```

The `// 'ons' //-best omitted` looks like someone considered adding it, but found too many drawbacks doing so.

I don't feel like patching in `synonym-optimizer`: too many cases and too many corner cases.
I don't want to change `snowball-stemmer.jsx`: it has not been changed for 6 years (it will be hard to publish), and there will be side effects.

I would say:
- your workaround using `identicals` is ok
- I might consider changing the stemmer for a new one - let me know if you have ideas

**Comment by blegaut** [comment]
Thank you Ludan. This is crystal clear.

I have no idea of a better stemmer for now.
