### ISSUE TITLE
[BUG] "ainsi que à les" contracts in "ainsi qu'à les"

### ISSUE THREAD

**Issue by blegaut** [RosaeNLG/rosaenlg#112]
**Describe the bug**
This French contraction seems wrong. 
"ainsi que à les" contracts in "ainsi qu'à les"

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**
I would expect that "ainsi que à les" contracts in "ainsi qu'aux"

**Code**
`p ainsi que à les`

**Context:**
 - RosaeNLG version: 3.1.2
 - Language: fr_FR,
 - Packaging: node.js, browser

**Additional context**

**Comment by ludans** [comment]
thanks @blegaut 
done
will be released in > 3.1.2

**Comment by ludans** [comment]
released in 3.2.0
