### ISSUE TITLE
[FEATURE] mixin with parameters in assembly

### ISSUE THREAD

**Issue by blegaut** [RosaeNLG/rosaenlg#115]
**Is your feature request related to a problem? Please describe.**
I would like to be able to pass some parameters to the mixins used in an assembly. However, I don't understand clearly if this is possible today and compatible with the params object sent by the assembly. Here a code sample:

```
mixin jaime(score, params)
  | score: #{score}
  if params
    | #[+toHtmlList(params)]
  case score
    when 1          
      | j'aime un peu
    when 2           
      | j'aime beaucoup
    when 3
      | j'adore

- var data = { score :1, products: ['pomme', 'abricot', 'haricot', 'hibiscus', 'houblon']};
p
  eachz elt in data.products with { separator: ',', last_separator: 'et', begin_with_general: jaime(data.score), end:'!' }
    | #[+value(elt, {det:'DEFINITE'})]
```

When executing this code, the score parameter received by the mixin is actually data.score, but the params parameter in which I expect the NonEmpty list is empty.

**Describe the solution you'd like**
I would like one of these two options:
- either that, in the previous code, the params object with the NonEmpty list will be send as the second parameter of the function
- either that, I can add to the params object a new key score with value I want to pass.

It would great if the solution allows the use of the same mixin with parameters, both in a standalone way , and within an assembly

**Describe alternatives you've considered**
I can use a global variable score that will be reachable within the mixin to avoid passing parameters, but I consider it a bad pattern

**Additional context**
Add any other context about the feature request here.

**Comment by ludans** [comment]
`jaime(data.score)` is a function call (not a reference to a function). It is evaluated to value '1' when generating the parameter. You will never have anything in the `params` of `jaime(score, params)`.

You can reference a function, as described here: https://rosaenlg.org/rosaenlg/3.2.0/mixins_ref/eachz_itemz.html#_when_assembling_knowing_which_elements_are_empty

I understand that you do not want to add a global variable for the second parameter.
But JavaScript has closures:

```
mixin jaime(score, params)
  | score: #{score}
  if params && params.nonEmpty && params.nonEmpty.length==3
    | and also
  else
    | and
- let WITH_3 = true;
p
  - let score = 1;
  itemz {mode:'single_sentence', separator: ',', last_separator: (params) => jaime(score, params)}
    item
      | first
    item
      | second
    item
      if WITH_3
        | third
```
will generate: _<p>First, second score: 1 and also third</p>_

Tell me if this is what you need.

**Comment by blegaut** [comment]
Thanks Ludan, this works perfect!
