### ISSUE TITLE
[BUG] misparsing "with" keyword in eachz

### ISSUE THREAD

**Issue by MathiasWinckel** [RosaeNLG/rosaenlg#116]
**Describe the bug**
when parsing the eachz with a "with" keyword, it fails if there is a "with" in the text parameters of the listing

**To Reproduce**
defines a basic eachz with a separator including "with" but with more text, it needs the extra " " arround
```
eachz _val in [1, 2] with { separator: "test with test" }
    | test
```
it will fail on parsing (or more precisely lexing) the eachz

```
> 2| eachz _val in [1, 2] with { separator: "test with test" }
--------------^
    3|     | test

Syntax Error: Unexpected token
    at makeError (H:\projects\migration\nodejs\maqs\node_modules\pug-error\index.js:32:13)
    at Lexer.error (H:\projects\migration\nodejs\maqs\node_modules\rosaenlg-pug-lexer\index.js:59:17)
```

**Expected behavior**
to be able to execute an eachz having "with" in its textual parameters

**Code**
Nothing to add

**Context:**
 - RosaeNLG version: 3.2.0.
 - Language: en_US
 - Packaging: node.js

**Additional context**
It can also fail using "with" in another parameter, not only "separator".
I looked into the lib with a debugger, and it seems that it does mistake the textual " with " for the keyword:
![image](https://user-images.githubusercontent.com/26458306/152841678-a39a9589-30a5-49ed-ad79-02eed4b38b6c.png)
thus mismatching the list and the assembly.

**Comment by MathiasWinckel** [comment]
I think I'm close to having a correction, but I could not manage to build the repo and run the tests yet...

Maybe I will be able to add a PR tomorrow. 
Or maybe you'll think of a more elegant way to handle it, here what I tried so far:

I tested adding a non greedy (`+?`) symbol in the part matching the list:
`/^eachz +([a-zA-Z_$][\w$]*) in ([^\n]+?) with ([^\n]+)/`
it works for " with " in the assembly, but it ends up not being able to handle a possible string including " with " in the list, mismatching the keyword on it.

I came up with a more verbose regex, regarding the matching of the list:
`^eachz +([a-zA-Z_$][\w$]*) in ([^\n"]+?|(?:[^\n"]*(?:"[^"]*"))+[^\n"]+?) with ([^\n]+)`
- it splits the matching of the list in two possibilities:
non greedy reading of non string listing: `[^\n"]+?`
greedy reading of the listing up to the start of a string, then match the string, keeps matching that, then end it with a non greedy reading to stop on the keyword: `(?:[^\n"]*(?:"[^"]*"))+[^\n"]+?`
- it requires a lot of non capturing groups `(?:`
- it can't handle \" in strings, still working on it
- it would not accept a variable "with" used as the list, but it seems bad practice to use keyword of a language as variable name...

**Comment by ludans** [comment]
Thanks @MathiasWinckel for spotting the bug and finding the solution.

The solution adding a non greedy `+?` is perfect. The regexp remains simple.

This case does NOT need to work:
```
- const with = [1, 2]
eachz _val in with with { separator: "test with test" }
  | bla
```
and anyway the developer has a simple workaround which is renaming the list.

Can you please do the PR?

Please add a new unit test with this kind of code:
```
//- Copyright 2022 ...
//- SPDX-License-Identifier: Apache-2.0
-
  util.expected = `
    Bla test bla
    bla test with test bla
    bla test with test bla
  `;

t
  l
    eachz _val in [1, 2] with { separator: "test" }
      | bla
  l
    eachz _val in [1, 2] with { separator: "test with test" }
      | bla

  l
    - const withList = [1, 2]
    eachz _val in withList with { separator: "test with test" }
      | bla
```

You say:
> I could not manage to build the repo and run the tests yet

The guide https://github.com/RosaeNLG/rosaenlg/blob/master/DEVELOPER_GUIDE.md#build-and-test should work.
Please open another ticket if you have issues, but building the code and running the tests should must be made simple.

**Comment by MathiasWinckel** [comment]
the issue with the simple solution, the non greedy symbol, is that a string including " with " in the list is no longer possible:

```
eachz _word in ["test with test", "text"] with { last_separator: "using with keyword" }
    | bla
```
will fail on the lexing, matching the keyword in the list. It simply displaces the matching issue before the keyword.
It seems less likely to happen than using "with" in a separator, imo, but could be possible, I guess...

Since it worked before my correction and would not after, I could not be the one making this call and wanted to find a better correction. That seems to work, and I think I got to handle \" in a string too.

But if it's what you want, I can go on with the simple solution.
And let the complex regex as a comment, just in case...

For the PR and the tests, I used the developer guide, but first I can't manage to build it entirely, failing on the documentation, then I can't run the whole test with `lerna run test`, failing on the linguistics resources. It would demand a new issue...
But for now, I can run the tests in `packages/rosaenlg` using `yarn test`, which runs the unit file and the foreach.pug testing template in which I wrote tests... and the other 2175 tests. If it's ok for you, I can make my PR with that.

**Comment by ludans** [comment]
A perfect solution is not doable with regexp. It would require a JavaScript parser, which is not available at lexer step. And you cannot (or at least should not) write a JavaScript parser using regexp.

I expect "with" to be used more in sepators etc. than in the list itself: that was your actual case.
So I would say that moving the problem is a good solution. 

You may create the PR. Github actions will run the regression tests.

And yes please open other tickets for the development environment setup.

**Comment by ludans** [comment]
solved in the PR
