### ISSUE TITLE
[BUG] +eatSpace requiring whitespaces to work properly

### ISSUE THREAD

**Issue by MathiasWinckel** [RosaeNLG/rosaenlg#119]
**Describe the bug**
the whitespace eater requires whitespaces both before and after to work, with its current regex to match

**To Reproduce**
evaluating:
```
| ( 
+eatSpace()
| test)
```
note: there is a space after (

it will produce:
> (EATSPACE test)

**Expected behavior**
to produce:
> (test)

seems to me eatSpace should simply remove whitespaces when they exist, but not requiring any to work

**Code**
If applicable, RosaeNLG template code and/or additional code that trigger your problem.

**Context:**
 - RosaeNLG version: 3.2.1
 - Language: en_US
 - Packaging: node.js

**Additional context**
a lot of time, spaces are added by rosaenlg/pug templating and it works...  I guess if it happens in my example because `(` remove the whitespaces first, I think it could be an issue under other circumstances if I dig a bit more...

It can be fixed by simply changing + to * in the regex matching whitespaces with the EATSPACE placeholder.
PR incoming.

**Comment by ludans** [comment]
done in v3.2.2
