### ISSUE TITLE
[BUG] displaying the empty list tags ul when the list is empty

### ISSUE THREAD

**Issue by MathiasWinckel** [RosaeNLG/rosaenlg#121]
**Describe the bug**
It displays the list tags `<ul></ul>` when the list is empty

**To Reproduce**

evaluating:
```
| testing empty bullets:
eachz elt in [] with { mode: 'list', if_empty: "the list is empty" }
    +value(elt)
```
will produce:
> Testing empty bullets: the list is empty `<ul></ul>`

with `<ul></ul>` at the end
note: `if_empty` being displayed, the list is seen as empty...

**Expected behavior**

to produce:
> Testing empty bullets: the list is empty

so not displaying the `<ul></ul>` when the list is empty

**Code**
If applicable, RosaeNLG template code and/or additional code that trigger your problem.

**Context:**
 - RosaeNLG version: 3.2.1
 - Language: en_US
 - Packaging: node.js

**Additional context**

I encountered 2 situations where it was problematic:
- when you have an `if_empty` it's more likely an alternative for commenting the empty list, so displaying the  <ul></ul> empty list seems not really useful and demands a post process step after rendering to get rid of them
- when you have no `if_empty` but your bullet list is in another bullet listing, the upper bullet list is now seen as not empty. 
Then an upper  `if_empty` sentence  was not triggered, and that's something you cannot fix with a post process step after rendering.
It seems it could defeat the empty text prediction in other circumstances...

It's quite easy to fix: the `<ul></ul>` are already added under condition (the asm mode), it simply requires to add a size check there.
PR incoming.

**Comment by ludans** [comment]
done in v3.2.2
