### ISSUE TITLE
[FEATURE] combining number in textual format with nominal group

### ISSUE THREAD

**Issue by blegaut** [RosaeNLG/rosaenlg#124]
**Is your feature request related to a problem? Please describe.**
I would like to be able to write, depending on the number of flowers, one of the following forms:

- une jolie fleur
- deux jolies fleurs
- trois jolies fleurs
- ...

However, I don't see how I can combine a number in textual value with a nominal group.
If I use two mixins such as
```
|#[+value(nb, {'TEXTUAL':true })] 
- const nbNumber = nb>1 ? 'P' : 'S'
|#[+value('fleur', { number: nbNumber, adj:'joli', adjPos:'BEFORE'})]
```
I will obtain "un jolie fleur" instead of "une jolie fleur" in the case nb === 1

**Describe the solution you'd like**
I would like a simle way to generate "une jolie fleur" or "deux jolies fleurs" base on the variable nb

**Describe alternatives you've considered**
An if then structure 

**Additional context**
Add any other context about the feature request here.

**Comment by ludans** [comment]
thanks @blegaut 
TEXTUAL numbers could not have a gender. For French it had an impact on "un" / "une" (always getting "un").

In the next version you will be able to use: `  l #[+value(1, {'TEXTUAL':true, agree: getAnonFS() })]`
and get "une"

**Comment by ludans** [comment]
done in v3.2.2

**Comment by blegaut** [comment]
Thank you Ludan
