### ISSUE TITLE
[FEATURE] How to change the Surface Realization mechanism of surround eachz items with white spaces?

### ISSUE THREAD

**Issue by imaxwel** [RosaeNLG/rosaenlg#126]
IMO, in Chinese, Japanese and Korean, there is no white space between "eachz" items.

**Comment by ludans** [comment]
Hello @imaxwel 
I should be able to implement that in the next weeks. 
Are you using RosaeNLG to generate content in these languages?
When you say Chinese, you mean Mandarin (not Cantonese)?

**Comment by imaxwel** [comment]
Thanks for ur instant reply! Looking forward to ur progress.
I'm using RosaeNLG to generate content in Mandarin Chinese, not Cantonese.

**Comment by ludans** [comment]
I just published 3.2.3.
Use `zh_CN` language.
I does not really support Chinese, but it stops adding spaces everywhere, including when using `eachz`.
Can you give it a try and make some feedback?
