### ISSUE TITLE
[BUG] "de des" doesn't contracts in French 

### ISSUE THREAD

**Issue by blegaut** [RosaeNLG/rosaenlg#127]
**Describe the bug**
This French contraction seems missing.
"de des" doesn't contracts, but it should contract in "de"

For instance
"La lecture de un procès-verbal prend du temps" contracts en  "La lecture d'un procès-verbal prend du temps"
"La lecture de des procès-verbaux prend du temps" doesn't contract.

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**
I would expect that "de des" contracts in "de".

For instance
"La lecture de des procès-verbaux prend du temps" would contract in "La lecture de procès-verbaux prend du temps" 

**Code**
`La lecture de des procès-verbaux prend du temps`

**Context:**
RosaeNLG version: 3.2.3
Language: fr_FR,
Packaging: node.js, browser

**Additional context**

**Comment by ludans** [comment]
Thanks @blegaut.
I agree.
Can you please make the change in the code and a PR?
https://github.com/RosaeNLG/rosaenlg/blob/master/packages/rosaenlg-filter/lib/LanguageFilterFrench.ts in `contrList`

**Comment by ludans** [comment]
Corrected on master. Will be in the next release.
