### ISSUE TITLE
[BUG] Numbers have spaces caused by punctuation filtering

### ISSUE THREAD

**Issue by bothness** [RosaeNLG/rosaenlg#128]
**Describe the bug**
The automatic punctuation filtering for commas and periods causes spaces to appear in numbers with thousand separators, eg. 1, 000, 000 and with decimals, eg. 1. 234

When one of the stated core uses of RosaeNLG is for for automating the production of financial reports, it would seem sensible to have an exception in the punctuation filtering for dealing with numbers rather than having to flag each number individually as an exception using "protect" or casing in § symbols.

**To Reproduce**
Type a number with commas or a decimal into your Pug template.

**Expected behavior**
RosaeNLG's punctuation filtering ought to include an exception for any string that includes a comma or period with numbers immediately before and after, eg. 0,0 or 0.0 - I can't think of a circumstance in natural language where strings like this should need a space added.

**Code**
Example noted above.

**Context:**
 - RosaeNLG version: 3.2.3
 - Language: en_US
 - Packaging: node.js / browser

**Additional context**
My use case for RosaeNLG is in semi-automated journalism, so my text includes quite a lot of numbers in various formats.

**Comment by ludans** [comment]
Thanks for reporting. 
The intended usage was that users would use 'value' tag mainly, as the numbers would be dynamic, and sometimes raw numbers, escaping them with 'protect'. 
If using a lot of raw numbers, it can be tedious and error prone. 
Maybe raw numbers can be automatically escaped before adding the spaces. 
I will have a look at that in the next days.

**Comment by ludans** [comment]
It should work properly on 3.2.4 version which I just published. Can you please give it a try?

**Comment by bothness** [comment]
Hi @ludans. Thanks for being so quick to respond to this. I'll give it a try tomorrow and report back on my experience.
