### ISSUE TITLE
[FEATURE] custom filters

### ISSUE THREAD

**Issue by reinoldus** [RosaeNLG/rosaenlg#130]
**Is your feature request related to a problem? Please describe.**
I put snippets of texts into mixins to make them reusable and in these mixins I add certain conditions to check if this text should render. For example a phone object like this:
```
{
"name": "Abc phone",
"has_5g": true
}
```

Right now I am creating mixins like this:
```
mixin 5g
    if phone.has_5g
          | has 5g
```

The problem is that there is no way in pug to tell if a mixin would return an empty result, so if I would like to create a header for example `<h1>Network connectivity</h1>`, it might render the header without any features below it, if there are no "network connectivity" features.

For this toy example I could work around it, but imagine you want to render a list of special features of a product that are not present on all products and where some do not have special features at all.

**Describe the solution you'd like**
If I am correct and I can't fix it within pug, I thought adding a custom filter like one of those would be useful: https://rosaenlg.org/rosaenlg/3.2.3/advanced/filter.html

This way I could add html comments and "regex them out" in case the list is empty

**Describe alternatives you've considered**
Fixing it through pug.
Regexing it after rosaenlg generated the text, but I'd prefer to configure everything in one place.

**Comment by ludans** [comment]
Thanks @reinoldus

Let's start from the code that does not work:
```
-
  const phone1 = {
    "name": "phone 1",
    "has_5g": true,
    "has_4g": true,
  }
  const phone2 = {
    "name": "phone 2",
    "has_5g": false,
    "has_4g": false,
  }

mixin phoneTest(phone)
  h2
    | network connectivity for #[+value(phone.name)]
  if phone.has_5g
    | has 5G.
  if phone.has_4g
    | has 4G.

p
  +phoneTest(phone1)
  | .
  +phoneTest(phone2)
```
generates:
```
Network connectivity for phone 1
has 5G. Has 4G.
Network connectivity for phone 2
```
The second title should not appear.


Let's continue with a simple solution (which is not so bad):
```
-
  const phone1 = {
    "name": "phone 1",
    "has_5g": true,
    "has_4g": true,
  }
  const phone2 = {
    "name": "phone 2",
    "has_5g": false,
    "has_4g": false,
  }
  
  function hasNetwork(phone) {
    return phone.has_4g || phone.has_5g
  }

mixin phoneTest(phone)
  if hasNetwork(phone)
    h2
      | network connectivity for #[+value(phone.name)]
    if phone.has_5g
      | has 5G.
    if phone.has_4g
      | has 4G.

p
  +phoneTest(phone1)
  | .
  +phoneTest(phone2)
```
generates:
```
Network connectivity for phone 1
has 5G. Has 4G.
```
It is relevant for some cases.


And let's finish with the best option, which is a very NLG oriented solution:
```
-
  const phone1 = {
    "name": "phone 1",
    "has_5g": true,
    "has_4g": true,
  }
  const phone2 = {
    "name": "phone 2",
    "has_5g": false,
    "has_4g": false,
  }
  
mixin networkTitle(phone)
  h2
    | network connectivity for #[+value(phone.name)]


mixin phoneTest(phone)
  - var params = phone; // trick if networkTitle mixin needs `phone` as a parameter
  itemz {begin_with_general: networkTitle}
    item
      if phone.has_5g
        | has 5G.
    item
      if phone.has_4g
        | has 4G.

p
  +phoneTest(phone1)
  | .
  +phoneTest(phone2)
```
generates:
```
Network connectivity for phone 1
has 5G. Has 4G.
```

`itemz` knows when the list is empty, and can generate or not the beginning depending on emptiness.
It avoids repeating the conditions in some javascript function.

**Comment by reinoldus** [comment]
Thank you for your long response.

I totally missed "itemz", it exactly does what I was looking for, Sorry for the spam!

------------------

For compensation:

I am working on a bash script hat renders the html output from "rosaenlg-cli " into plain text with proper formatting right on the shell, because otherwise it is hard to read the text output if it's just one html blob.


I am using pandoc for the conversion https://pandoc.org/ and some "bash magic".

My current solution looks like this:

```
#!/bin/bash

while read -r line
do
  if [[ $line =~ "BASH-START" ]]; then
    echo "$line" | pandoc --from html --to plain --wrap=auto --columns 100
  else
    echo "$line"
  fi

done < "${1:-/dev/stdin}"
```

This bash program basically continuously reads the stdout of "npx rosaenlg-cli -w -l en_US templates/products/summary/cli.pug" and runs pandoc, if a trigger word is present in the line.

I put a simple comment into my cli file: `//BASH-START` . All the other lines are just printed normally.
At the end of the file you have to put "| \\n", we need this because "read" waits for a line break to return the net line and enter the loop, The problem is: there are no line breaks in pug, so I am using the "-r" flag of `read` which tells it to ignore escaped line breaks.

A typical CLI entry file looks like this:
```
//- Bash comment to tell pandoc to render
//BASH-START
include entry //- Import the "real root file
//- Line break hack
| \\n
```

The program is then ran as follows: "npx rosaenlg-cli -w -l en_US templates/products/summary/cli.pug | ./html2plain.sh"

It will turn:
```<ul><li>Aaaa</li><li>Xxxx</li><li>Sss</li><li>Fff</li><li>S</li></ul>```

into
![image](https://user-images.githubusercontent.com/2091290/181711723-8c6006bd-fc36-4527-bbac-985c15c6fd9e.png)



Current issues with this program (after that it works fine):
- The entire html output has to be on one line


It's massively OT, but I thought it might be useful, but I didn't want to open another ticket for it. I hope it is helpful!

**Comment by ludans** [comment]
Thanks. Let's leave this recipe here, as it can be useful for other users.
Having a proper development environment around RosaeNLG (or NLG in general) is not simple.
If you refine your scripts, you might do a PR to it in RosaeNLG's documentation, maybe here: https://rosaenlg.org/rosaenlg/3.2.4/integration/rosaenlg-cli.html
