### ISSUE TITLE
[BUG] span eats space between words

### ISSUE THREAD

**Issue by blegaut** [RosaeNLG/rosaenlg#150]
**Describe the bug**
when I add a span around a word, the space after that word are eaten by rosae

**To Reproduce**
```
span les bouquets 
| garnis
```
produces
`<span>les bouquets</span>garnis`

**Expected behavior**
I would expect `<span>les bouquets</span> garnis` or eventually `<span>les bouquets </span>garnis` depending if I added a space after bouquets

**Code**
```
span les bouquets 
| garnis
```
note that a workaround is to insert a protect after the span

```
span les bouquets 
protect
| garnis
```

**Context:**
 - RosaeNLG version: 3.2.5
 - Language: fr_FR
 - Packaging: node.js, browser

**Additional context**

**Comment by ludans** [comment]
Thanks @blegaut - the bugs regarding spaces are always the most pleasant ones :)

It was a bug indeed, that uncovered another small bug in lists management.
Will be shipped with next release.
Tell me if you need it early.

**Comment by ludans** [comment]
done in 3.2.6
