### ISSUE TITLE
[BUG] numbers come unprotected when used in a protect tag

### ISSUE THREAD

**Issue by MathiasWinckel** [RosaeNLG/rosaenlg#158]
**Describe the bug**

numbers come unprotected when used in a `protect` tag

**To Reproduce**

Any number in a protect tag seems to reproduce this issue:

a basic template printing a html header in a protect tag, my real use case:
`protect <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">`

and/or a simple number under a protect tag, I tried when isolating the issue:
```
protect 
    | 4.01
```

**Expected behavior**

I would that to produce:
> < !DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
> 4.01

but it will produce:
> < !DOCTYPE html PUBLIC "-//W3C//DTD HTML 4. 01//EN" "http://www.w3.org/TR/html4/strict.dtd">
> 4. 01

seeing the decimal separator as a period punctation symbol. 
(unrelated, but I had to add a space at the start of the header  _< !DOCTYPE_ to get it to appear in a formatted text here, it actually produced _<!DOCTYPE_  correctly )

**Code**

Nothing to add, see additional context for more information.

**Context:**
 - RosaeNLG version: 3.2.6
 - Language: en_US (but I think it would come up in any language)
 - Packaging: node.js

**Additional context**
I don't have an immediate solution.
It seems to only come up in my html header so far, so I can go with a work around and I have to finish some stuffs before I could get back to that issue, if you don't have time to investigate right away.

Here the result of my investigation, if it can help:

So far, I was able to find out that the engine will have to process the following text before punctation :

`'START. §¤<!DOCTYPE html PUBLIC "-//W3C//DTD HTML §4.01§//EN" "http://www.w3.org/TR/html4/strict.dtd">¤§§¤ ¤¤§4.01§¤§'`

so with additional § protect symbol around the number, while it was already "inside" § symbol, thus clausing and reopening the protection around the numbers.

I also was able to get to the part of your `filter` process (_node_modules\rosaenlg-filter\dist\index.js, filter function_) doing that:
```
  // ADD START to avoid the problem of the ^ in regexp
    res = 'START. ' + res;
>  res = languageFilter.protectRawNumbers(res);
    res = languageFilter.beforeProtect(res);
    // PROTECT § BLOCKS
    const protectedMappings = protect.protectBlocks(res);
```
`languageFilter.protectRawNumbers` being the one trying to protect number without taking into account their current protected status

So it seems related to the issue #128  and commit #129 which introduced that.

I don't know if there is already something to tell you if a text is inside a protection you could use when maching the number?
I'm not sure it would be possible for protectRawNumbers to check through its number matching regex if the number already inside a protected text. Seems quite complex... 
But maybe using another regex matching for protected text and comparing text index once a number is found to dedude if its inside a protected text? That may be pretty bad, performance-wise.

**Comment by ludans** [comment]
Thanks @MathiasWinckel  for the report and the analysis, which is accurate.

The general is about nesting of protections, which do not work properly.
```
protect
  protect
    | bla.bla
```
generates `bla. Bla` - which is not good, should remain `bla.bla`

Automating protections for numbers just increased the scope of this existing problem.

It will not be easy to solve, I think the underlying protection mechanism needs some review.
I'll have a look a it.

**Comment by ludans** [comment]
@MathiasWinckel please check with 3.3.1
