### ISSUE TITLE
[BUG] Islands are missing grammatical information, in french 

### ISSUE THREAD

**Issue by MathiasWinckel** [RosaeNLG/rosaenlg#159]
**Describe the bug**

The "Îles Féroé" are missing "ale" form (=> "aux Iles Féroés")
it's also missing gender and plural information, to use with a determiner.

After taking a look, a lot of the islands in the french ressource appear to have the same issue (more than 20 entries, for what I counted) but some like Ile Maurice are ok.

**To Reproduce**

```
+country({ cca2: "FO"  }, 'IN')
+country({ cca2: "FO"  }, 'DEFINITE')
```

first will tell you that "ale" is missing when using IN
second will tell you a "gender" is missing when using DEFINITE, but it's also lack the plural data to be correct

**Expected behavior**
to produce: 
> Aux Îles Féroé les Îles Féroé

**Code**

**Context:**
 - RosaeNLG version: 3.2.6 ("rosaenlg-countries": "2.0.1")
 - Language: fr_FR (don't know about other languages)
 - Packaging: node.js

**Additional context**
I have a more complete rosaenlg-countries\dist\countries_fr_FR.js file that I used as a quick fix, I could push it to you if you let me some time to finish what I'm up to right now.
Or would you want that to be corrected any other way?

**Comment by ludans** [comment]
Thanks Mathias.
Let me check how it was generated first - maybe there is an update on the
source (though I'm not confident at all).
Anyway it would be useful to have the corrected file, both to correct on
RosaeNLG as a patch, and possibly also to update the source data.


Le jeu. 9 févr. 2023 à 13:48, Winckel Mathias ***@***.***> a
écrit :

**Comment by ludans** [comment]
I updated the source from 4.0.0 to 4.1.0 - it didn't have much positive impact.
For cases like this, you may update `deFr.txt` and `rawFr.csv`. See example on Féroé: https://github.com/RosaeNLG/rosaenlg/commit/072ee9ef45467d6782d68e16ad7dad567de3982d

Can you please complete the PR?
Please add 2-3 random tests on what you add just to check the syntax in `test_fr_FR_Islands.pug` (no need to be exhaustive).

**Comment by ludans** [comment]
@MathiasWinckel can you please have a look? I would like to be able to finish and close the PR (with more content than just Iles Féroé).
