### ISSUE TITLE
[BUG] timezone issue in documentation

### ISSUE THREAD

**Issue by blegaut** [RosaeNLG/rosaenlg#161]
**Describe the bug**
Reading the documentation website from Colombia (timezone UTC -5), the value date doesn't provide the expected result

![image](https://user-images.githubusercontent.com/92172115/220941135-67cebacc-1855-4930-95aa-6e5605544fdb.png)

As far I understand, the date is created on the UTC time because to hours are indicated. See below

![image](https://user-images.githubusercontent.com/92172115/220941988-9939bbc3-5ea7-46ed-8502-b3028ab1aa89.png)

**To Reproduce**

**Expected behavior**
I would like the expected result to be independent of the local timezone of the computer. This is particularly important in case one wants to contribute and need to run the tests locally before proposing a PR

**Code**
If applicable, RosaeNLG template code and/or additional code that trigger your problem.

**Context:**
 - RosaeNLG version: 3.3.1
 - Language: all
 - Packaging: browser, node

**Additional context**

**Comment by ludans** [comment]
Thanks for spotting. The date is created UTC, but displayed using local time zone, which will often lead to differences. 
It can be replayed easily by changing the localy in the browser. 
Both must be aligned for tests. The issue happens here, in the doc, but in other automated tests as well. 
I don't think there is an issue with RosaeNLG itself, it is probably only on the tests.  

I think that I will make date creation and date printing both aligned with local time zone for the tests.
And I will document it.

**Comment by ludans** [comment]
done in 3.4.0
