### ISSUE TITLE
[BUG] done() called multiple times in rosaenlg-node-server:test

### ISSUE THREAD

**Issue by blegaut** [RosaeNLG/rosaenlg#170]
**Describe the bug**
In the dev environment, sometimes the tests in `rosaenlg-node-server:test` will failwith the following message

```
 1) persistence
              cannot save template
                "after all" hook in "cannot save template":
            done() called multiple times in hook <persistence cannot save template "after all" hook in "cannot save template"> of file 
```

**To Reproduce**
eventually run the tests on a Mac

**Expected behavior**
The tests should run ok.

**Code**
If applicable, RosaeNLG template code and/or additional code that trigger your problem.

**Context:**
 - RosaeNLG version: 3.4.0
 - Language: [e.g. en_US, fr_FR, etc.]
 - Packaging: dev environnement

**Additional context**
The problem is easily solved by adding a done. I am doing a PR
![image](https://user-images.githubusercontent.com/92172115/222293241-5b83676d-c875-4114-b2e5-8e966947cbd5.png)

**Comment by ludans** [comment]
solved thanks to your PR #171
