### ISSUE TITLE
[BUG] french adjective possessive doesn't adapt to next word

### ISSUE THREAD

**Issue by blegaut** [RosaeNLG/rosaenlg#180]
**Describe the bug**
Rosae generates `ma intuition` instead of `mon intuition`

**To Reproduce**
`| #[+value('intuition', {det:'POSSESSIVE', personOwner: 1})]`

**Expected behavior**
Even if intuition is `FEMININE`, the text should be '`mon`' for euphonic reason.

**Code**
`| #[+value('intuition', {det:'POSSESSIVE', personOwner: 1})]`

**Context:**
 - RosaeNLG version: 4.00
 - Language:  fr_FR
 - Packaging: node.js, browser

**Additional context**
I'll do a PR soon

**Comment by ludans** [comment]
Thanks @blegaut for spotting and correcting the bug and adding new cases
Will be shipped in > 4.0.0
