### ISSUE TITLE
[BUG] additional space when use value without adjectives

### ISSUE THREAD

**Issue by blegaut** [RosaeNLG/rosaenlg#182]
**Describe the bug**
When calling ` nlgLib.valueManager.value` in no-pug mode. Depending on the parameters, the text produced has additional space before and after the generated text. This is mostly an issue in no pug mode. 

**To Reproduce**
See code below

**Expected behavior**
I would expect that space are never added, which would be with the code below:

`No-space-afteravion no-space-afterhomme bleu no-space-afterun homme bleu`

**Code**
```
    const nlgLib = new NlgLib({ language: 'fr_FR' });
    nlgLib.spy.appendPugHtml('no-space-after');
    nlgLib.valueManager.value('avion');

    nlgLib.spy.appendPugHtml(' ');
    nlgLib.spy.appendPugHtml('no-space-after');
    nlgLib.valueManager.value('homme', { adj: 'bleu' });

    nlgLib.spy.appendPugHtml(' ');
    nlgLib.spy.appendPugHtml('no-space-after');
    nlgLib.valueManager.value('homme', { det: 'INDEFINITE', adj: 'bleu' });
    
    const rendered = nlgLib.getFiltered();
```
will produce

`No-space-afteravion no-space-after homme bleu no-space-afterun homme bleu`

**Context:**
 - RosaeNLG version: 4.0.0
 - Language: fr_Fr, en_Us
 - Packaging: node.js

**Additional context**
Please look at my related PR

**Comment by ludans** [comment]
thanks for spotting the bug and for the nice PR
