### ISSUE TITLE
[BUG] synonym mode 'once' not working properly

### ISSUE THREAD

**Issue by blegaut** [RosaeNLG/rosaenlg#187]
**Describe the bug**
The synonym mode 'once' doesn't exclude previously triggered synonyms when calling nlgLib.synManager.runSynz with an empty array as exclude parameters

**To Reproduce**
Run the synonym mode 'once'  by calling:
(method) SynManager.runSynz(which: MixinFct, whichName: string, size: number, params: RunSynzParams, excludeParam: number[]): void
with excludeParam: []

**Expected behavior**
previously triggered synonyms should be excluded if possible

**Code**
If applicable, RosaeNLG template code and/or additional code that trigger your problem.

**Context:**
 - RosaeNLG version: 4.1.0
 - Language: fr_FR
 - Packaging: rosaenlg-lib

**Additional context**
I am creating  a PR that solves the issue

**Comment by ludans** [comment]
hello @blegaut 

When using RosaeNLG in template mode, the call to `runSynz` is generated, and `excludeParam` is not set in the first call.

`excludeParam` is an internal parameter that RosaeNLG manages when `runSynz` is called.

Why do you need to specify it when calling it programmatically? Can't you just avoid using the parameter (and maybe make it optional in the signature)?

**Comment by blegaut** [comment]
Perfect. I updated the PR accordingly (making the parameter optional)
