### ISSUE TITLE
[BUG] protect tag :  through api , it generates a protect HTML tag < Protect> and unprotected strings

### ISSUE THREAD

**Issue by jaaf85** [RosaeNLG/rosaenlg#199]
**Describe the bug**
Hi Ludan,
i get a weird behavior with the protect tag through APi result in fr_FR.

i want to produce hashtags. i used the protect tag wich is very helpful in rosae  webeditor and it protects from the filtering mechanisms. However after deploying it in API, i get an other response : non protected, with an html protect tag. 
Here is an exemple produced through api after deploying the generated template in rosae Editor
<protect># veste courte</protect> 

**To Reproduce**
here is the the code used to produce what i expect in rosaenlg editor :
        protect 
          | ##[+value(apparel.name)]#[+agreeAdj(apparel.length, apparel.name)]
in the editor i get the expected result in html or raw : #vestecourte
but through APi i get 
<protect># veste courte</protect>

**Expected behavior**
through api i want to get the same result as the editor 

thanks in advance for your help !

**Code**
        protect 
          | ##[+value(apparel.name)]#[+agreeAdj(apparel.length, apparel.name)]

**Context:**
 - RosaeNLG version: rosae editor + deploing the template in node js version
 - Language: fr_FR
 - Packaging: node.js & browser

**Comment by ludans** [comment]
This is the exact code in my template:
```
-
  const apparel = {
    name: 'veste',
    length: 'courte',
  };

protect
  | ##[+value(apparel.name)]#[+agreeAdj(apparel.length, apparel.name)]
```

I use the JSON export from the Web IDE:
![image](https://github.com/RosaeNLG/rosaenlg/assets/20767031/9b3d47e9-70fc-4d12-bbe4-effcfe3588a9)
(but you can use https://rosaenlg.org/rosaenlg/4.2.2/integration/rosaenlg_packager.html as well)

I get this packaged template:
```
{
  "templateId": "protect",
  "src": {
    "entryTemplate": "protect.pug",
    "templates": {
      "protect.pug": "-\n  const apparel = {\n    name: 'veste',\n    length: 'courte',\n  };\n\nprotect\n  | ##[+value(apparel.name)]#[+agreeAdj(apparel.length, apparel.name)]\n"
    },
    "compileInfo": {
      "activate": true,
      "compileDebug": false,
      "language": "fr_FR"
    }
  },
  "format": "2.0.0"
}
```

I create the template in the API, with Postman or cURL:
```
curl --location --request PUT 'localhost:5000/templates' \
--header 'Content-Type: application/json' \
--data-raw '{
  "templateId": "protect",
  "src": {
    "entryTemplate": "protect.pug",
    "templates": {
      "protect.pug": "-\n  const apparel = {\n    name: '\''veste'\'',\n    length: '\''courte'\'',\n  };\n\nprotect\n  | ##[+value(apparel.name)]#[+agreeAdj(apparel.length, apparel.name)]\n"
    },
    "compileInfo": {
      "activate": true,
      "compileDebug": false,
      "language": "fr_FR"
    }
  },
  "format": "2.0.0"
}'
```

Then I render it:
```
curl --location --request POST 'localhost:5000/templates/protect/7f586705d90d95ae4703f88c3244d7274a4e8846/render' \
--header 'Content-Type: application/json' \
--data-raw '{
  "language": "fr_FR"
}'
```

I get the proper result:
```
{
    "renderedText": "#vestecourte",
    "renderOptions": {
        "language": "fr_FR",
        "randomSeed": 974
    },
    "outputData": {},
    "templateSha1": "7f586705d90d95ae4703f88c3244d7274a4e8846",
    "ms": 0.632099986076355
}
```

Maybe there is an issue when packaging the template. Can you please check?

**Comment by jaaf85** [comment]
Hi Ludan,

I have found the issue thanks to your detailed response.  Its related to an outdated runtime version. I was on a 3.2.6 for my rosaenlg-server on node and it might be an incompatibility on the protect flag
In fact,  i tested the same steps as you and still found my error. so i understood that it wasn't template related but infratsructure related. 

So it isn't a bug but a problem on my setup ! 
Thank you very much for your help and also for your wonderful product
