### ISSUE TITLE
[FEATURE] make languageImpl accesible in library mode

### ISSUE THREAD

**Issue by blegaut** [RosaeNLG/rosaenlg#200]
**Is your feature request related to a problem? Please describe.**
I want to make languageImpl accesible in library mode, so I can add custom dictionary

**Describe the solution you'd like**
adding a getter 

**Describe alternatives you've considered**

**Additional context**

PR created

**Comment by ludans** [comment]
Thanks for the PR. Tell me if you need a release (I did not plan to release soon).
