### ISSUE TITLE
[FEATURE] more pronouns in French sentence

### ISSUE THREAD

**Issue by blegaut** [RosaeNLG/rosaenlg#202]
**Is your feature request related to a problem? Please describe.**
I would like to be able sentences such as:
"Il nous invite ...."
"Ils nous en remercient"

**Describe the solution you'd like**
extend the `sentence` `mixin` by adding two optional parameters

- within the `params`, `person` to describe the person of direct or indirect object
- `pronounForm` to pass a `mixin` as the way to write a non-supported pronoun such as _en_, _y_

**Describe alternatives you've considered**

**Additional context**
I created a PR with a possible implementation

**Comment by ludans** [comment]
Thanks @blegaut 
I understand the need and the PR looks fine. Yet I cannot say if there are edge cases missing.
Do you see limitations / things to check in your PR?
If not, I will merge.

**Comment by blegaut** [comment]
I can't really see edge cases right now. I believe that the pronounForm will help anyways if you need to support unexpected edge cases

**Comment by ludans** [comment]
understood - thanks!
