### ISSUE TITLE
[FEATURE] Passive voice in French

### ISSUE THREAD

**Issue by blegaut** [RosaeNLG/rosaenlg#204]
**Is your feature request related to a problem? Please describe.**
I would like to be able to use **passive voice** and more **tenses** in the `sentence` mixin in French, writing for isntance:
"Elle n'aurait jamais été aperçue."

**Describe the solution you'd like**
add functionality to the package french-verbs and then to the mixin `sentence` in French

**Describe alternatives you've considered**

**Additional context**
I created a PR with a possible implementation

**Comment by ludans** [comment]
Thanks a lot for your PR. Looks fine, as usual.
I added a few small comments. You can move forward.

**Comment by ludans** [comment]
@blegaut I merged
