### ISSUE TITLE
[FEATURE] verb pacser is not supported in French

### ISSUE THREAD

**Issue by blegaut** [RosaeNLG/rosaenlg#206]
**Is your feature request related to a problem? Please describe.**
When I tried to use the verb _pacser_ in a mixin, I got the following error:

`NotFoundInDict: pacser not in dict`

**Describe the solution you'd like**
I would like to be able to update the list of supported verbs

**Describe alternatives you've considered**
Not sure what would be the best approach.
Maybe, for an unknown verb, finishing with `er`, we should automatically consider that is a regular verb from the 1er group.

**Comment by ludans** [comment]
Suggest to add the new verbs in french-verbs-lefff package: directly in JavaScript.

**Comment by ludans** [comment]
4.4.0 done
