### ISSUE TITLE
[BUG] Error with regular verbs ending in a single vowel followed by a single consonant (not doubling the last consonant)

### ISSUE THREAD

**Issue by Andergraw** [RosaeNLG/rosaenlg#210]
**Describe the bug**
According to English grammar, monosyllabic verbs or verbs with the final syllable stressed ending in a single vowel followed by a single consonant should double the last consonant before adding -ed (or -ing). They appear in the irregular gerunds list but they are not spelled correctly in the past tense forms.

**To Reproduce**
Try verbs like ship, stop or plan.

**Expected behavior**
Those verbs should double the last consonant in the past tenses. 

**Code**
If applicable, RosaeNLG template code and/or additional code that trigger your problem.

**Context:**
 - RosaeNLG version: english-verbs-helper v3.3.0
 - Language: english
 - Packaging: browser (npm)

**Additional context**

**Comment by ludans** [comment]
Thanks for reporting and analysing. 
I confirm the issue. 
I will try to solve and release this weekend.

**Comment by ludans** [comment]
You may use 4.3.1.
I added a quite extensive list of such verbs (a rule does not really work, there are plenty of exceptions).

**Comment by Andergraw** [comment]
Thank you for the quick response!
