### ISSUE TITLE
[BUG] No indication of German verbs with detachable prefix 

### ISSUE THREAD

**Issue by franklindyer** [RosaeNLG/rosaenlg#211]
**Describe the bug**
When conjugating separable verbs in German, `getConjugation` gives no indication that the verb is separable. For instance, conjugating `anschauen` in 1st person singular Präsens returns `["anschauen"]`.

**To Reproduce**
```
console.log(GermanVerbsLib.getConjugation(GermanVerbsDict, "anschauen", 'PRASENS', 1, 'S')); 
// Returns ["anschaue"] rather than ["schaue an"] or ["schaue", "an"]
```

**Expected behavior**
Some indication should be given for verbs that have a detachable prefix such as `"an"`. For other multi-part conjugations in which the pieces may show up in different parts of the sentence, e.g. `"habe angeschaut"`, the behavior of `getConjugation` is to return the parts as separate elements in an array i.e. `["habe", "angeschaut"]`. For maximum consistency, detachable particles should also be treated this way, e.g. returning `["schaue", "an"]` in my example case.

As a user of the library, it is nontrivial to rig up a patch for this bug. It requires knowing precisely which verbs have a separable prefix, which cannot be known a priori by checking for the presence of a certain prefix. For instance, not all verbs starting with `"an"` in the infinitive have `"an"` as a separable particle, for instance "analysieren" does not.

**Code**
See "to reproduce" above.

**Context:**
 - RosaeNLG version: `german-verbs@5.3.1` and `german-verbs-dict@3.3.1`
 - Language: de_DE
 - Packaging: node.js, Safari

**Comment by ludans** [comment]
hello @franklindyer, thanks for reporting and the first analysis, mine is below, please tell me if that looks good before I implement.

- There are multiple such prefixes.
For "schauen": abschauen, anschauen, aufschauen, ausschauen, etc.

- The prefix is not put before the verb when conjugating:
	"ich anschaue" is not valid. 
	"ich schaue an" is valid.
	But when having a past participle: "ich habe angeschaut".

- There can be other things between the verb and the prefix: e.g. "ich schaue mir das an".

- There are exceptions:

"beschauen" => "ich beschaue" (and not "ich schaue be"). Could be related to "be" prefix in general.
"durchschauen" => "ich durchschaue" or "ich schaue durch". Both are OK.
"überschauen" => "ich überschaue". "ich schaue über" exists but would possibly not constructed using "überschauen" verb.


- What are the rules?

inseparable prefixes: be, emp, ent, er, ge, miss, ver, voll, zer
separable: ab, an, auf, aus, bei, da, ein, fern, fort, her, hin, los, mit, nach, um, unter, vor, weg, weiter, wieder, zu, zurück, zusammen, drein, empor, hervor, hierher, hinüber, umher, voraus
a few prefixes which can be separable or inseparable, even when attached to the same root verb: durch, über, um, unter, wieder

- What I plan to do:

1. Detect the cases:
	If a verb (e.g. "durchschauen") starts with a separable prefix (here "durch") and the other part exists (here "schauen"), then it is a "verb with prefix". This should eliminate cases like "analysieren".
	Ignore inseparable prefixes (no change of behavior).
	Prefixes that can be separable or inseparable will be considered as separable (up to the end user to decide).
	Store accordingly.
2. New tag `+verbPrefix`

As nice examples for tests: beschauen, durchschauen, überschauen.

**Comment by franklindyer** [comment]
That looks good to me. Regarding your example "beschauen": yes, I think the `be-` prefix is always inseparable.

I'm also happy to take a crack at implementing this and make a PR, if you want. Let me know. :-)

**Comment by ludans** [comment]
I started working on it earlier, and, well, I finished.
Help proposal is largely appreciated - next time we can split the work.

You may test using version 4.4.0.

Doc is here: https://rosaenlg.org/rosaenlg/4.4.0/mixins_ref/verbs_german.html

**Comment by franklindyer** [comment]
That was quick - thanks a lot for the fix!

**Comment by ludans** [comment]
4.4.0 done
