### ISSUE TITLE
[BUG] valueToSorP(val) does not classify a val of 0 as 'P' in English

### ISSUE THREAD

**Issue by bethMc615** [RosaeNLG/rosaenlg#26]
**Describe the bug**
When the value passed to valueToSorP() is 0, the function will incorrectly return 'S'. In English, zero of an item should be plural.
Example: 0 cars, 1 car, 2 cars

**To Reproduce**
In the RosaeNLG IDE enter:
```
- var data = [0, 1, 2];
eachz item in data with { separator: ',', last_separator: 'and' }
  | #{item} #[+value('car', {number: valueToSorP(item)})]
```
Renders: 0 car, 1 car and 2 cars

Expected render:  0 cars, 1 car and 2 cars

**Context:**
 - RosaeNLG version: 2.0.0
 - Language: English

**Comment by ludans** [comment]
I confirm the issue.
It has both to be finer and language specific.

in English:
0 cars
1 car
1,5 miles

in French:
0 kilomètre
1 kilomètre
1,5 kilomètre
2 kilomètres

have to check in Italian, German and Spanish too.

I might do it and release a new version this weekend.

**Comment by ludans** [comment]
done in v2.1.0, just published

**Comment by bethMc615** [comment]
Thank you!
