### ISSUE TITLE
Add 'to be' to the list of irregular verbs

### ISSUE THREAD

**Issue by NamelessOne13** [RosaeNLG/rosaenlg#55]
Seems like the verb "to be" is missing in the list of all irregular verbs. Would be awesome if you could add one

**Comment by ludans** [comment]
Thanks @NamelessOne13 

In v2.1.7:

In `english-verbs-irregular` package, I added `"be":[["was","been"],["were","been"]]` in `resources/verbs.json`.

If you need to conjugate English verbs I suggest using `english-verbs-helper`: it uses the resources and adds conjugations and gerunds (ing).
