### ISSUE TITLE
[FEATURE] Nested mixins

### ISSUE THREAD

**Issue by jeanvittor** [RosaeNLG/rosaenlg#79]
Hi,

And I'd like to express a kind of query, I mean a set of criteria, into a paragraph. And I'd like to control a bit the phrasing. For example, choose a couple of criteria (if they're present) and express them into a sentence, then pack other criteria into another sentence, then pack the remain into a last sentence (all sentences being in the same paragraph).

Let's consider the following json data:

`{
    myShape: {
	rectangle: {length: '1 m', width: '48 cm'},
	thickness: '10 cm',
	color: 'rouge',
	matter: 'terre'
    }
}`

I'd like to generate something like:

`<p>Je veux un rectangle de terre. Je veux qu'il soit rouge et qu'il soit épais de 10 cm. Je veux qu'il soit long de 1 m et large de 48 cm.</p>`

Roughly, the generated paragraph contains 3 sentences:

- one giving matter and shape,
- one giving color and thickness,
- one refining geometrical properties.

I'm a bit lost between JS functions, Pug mixins and RosaeNLG features. My understanding is that NLG features (e.g. leading to sentences) are available at top-level or in mixins and that mixin return value does not go under the html node scope.

Is there a way to use some NLG features inside some kind of functions that could be invoked in a call site that is constructing a paragraph?
What do I miss?

Thanks,
Jean

**Comment by ludans** [comment]
Thanks @jeanvittor 

I would suggest to go through the French tutorial first at https://rosaenlg.org/rosaenlg/3.0.0/tutorials/tutorial_fr_FR.html as it is a good entry point for NLG in general.

In practice, this code:
```pug
- 
  const myShape = {
    type: 'rectangle',
    length: '1 m', 
    width: '48 cm',
    thickness: '10 cm',
    color: 'rouge',
    matter: 'terre'
   };

mixin myShape_ref(obj, params)
  | #[+value(myShape.type, { det: 'INDEFINITE' })]
  - setRefGender(myShape, myShape.type);
- myShape.ref = myShape_ref;

mixin myShape_refexpr(obj, params)
  | #{getMFN(['il', 'elle'], myShape)}
- myShape.refexpr = myShape_refexpr;


mixin matterShape
  | je veux
  | #[+value(myShape)]
  | de
  | #[+value(myShape.matter)]
  

mixin colorThickness
  | je veux que
  | #[+subjectVerb(myShape, {verb: 'être', tense: 'SUBJONCTIF_PRESENT'})]
  itemz {separator: ', ', last_separator: 'et'}
    item
      | #[+value(myShape.color)]
    item
      | épais de
      | #[+value(myShape.thickness)]
  
mixin sizes
  | je veux que
  | #[+subjectVerb(myShape, {verb: 'être', tense: 'SUBJONCTIF_PRESENT'})]
  itemz {separator: ', ', last_separator: 'et'}
    item
      | long de
      | #[+value(myShape.length)]
    item
      | large de
      | #[+value(myShape.width)]
  
  

p
  itemz { mode: 'sentences', separator: '.' }
    item
      | #[+matterShape]
    item
      | #[+colorThickness]
    item
      | #[+sizes]

```

will output:
```html
<p>Je veux un rectangle de terre. Je veux qu'il soit rouge et épais de 10 cm. Je veux qu'il soit long de 1 m et large de 48 cm.</p>
```


If you have plenty of properties, and if they are dynamic (only known at runtime), you might adapt the code to make it more generic; but it will be difficult to manage the texts which are specific for each property, like 'épais de' for thickness.

**Comment by jeanvittor** [comment]
Great!
Thanks @ludans .
