### ISSUE TITLE
[FEATURE] Polymorphism with RosaeNLG

### ISSUE THREAD

**Issue by jeanvittor** [RosaeNLG/rosaenlg#80]
Hi,

I'd like to use some kind of polymorphism with RosaeNLG.

I want to generalize some properties and let implementations provide a formulation.
An example use case could be taken from what I've described in https://github.com/RosaeNLG/rosaenlg/issues/79.
Now, I'd like to write a JS root class (say Criterion) which would be derived (extended) e.g.:
```javascript

class Criterion {} // Empty, but I know that subclasses will implement a function formulate().

class QuantityCriterion extends Criterion {
  constructor (quantity) {
    super();
    this.quantity = quantity;
  }
  // This function is the one I want to implement for each concrete class.
  formulate() {
    return this.adjective + ' de ' + this.quantity;
  }
}

// An example of subclass. Another one could be provided for thickness.
class LengthCriterion extends QuantityCriterion {
  constructor (length) {
    super (length);
    this.adjective = 'long';
  }
}
```
And in the template:
```
- var c = new LengthCriterion ('1 m');

p
  | je veux que
  | #[+subjectVerb(myShape, {verb: 'être', tense: 'SUBJONCTIF_PRESENT'})]
  | #{c.formulate()}
```

Which should give:
```html
<p> je veux qu'il soit long de 1 m.</p>
```
My problem is that I would like to use some NLG features in the implementation of the function `formulate()`. And it looks like I can't.

Is there such a polymorphism in which I could use NLG features?

Thanks,
Jean

**Comment by ludans** [comment]
RosaeNLG (and Pug) are more like (simple) functions, there's no real polymorphism.

A good (yet not absolute) practice is to keep all the texts in templates, not managing texts as strings in JavaScript functions.

In practice, this is what I would do: a big simple switch / case:

```pug
- 
  const myShape = {
    type: 'rectangle',
    length: '1 m', 
    width: '48 cm',
    thickness: '10 cm',
    color: 'rouge',
    matter: 'terre'
   };

mixin myShape_ref(obj, params)
  | #[+value(myShape.type, { det: 'INDEFINITE' })]
  - setRefGender(myShape, myShape.type);
- myShape.ref = myShape_ref;

mixin myShape_refexpr(obj, params)
  | #{getMFN(['il', 'elle'], myShape)}
- myShape.refexpr = myShape_refexpr;

-
  function getProps() {
    // could be dynamic, taking all props and excluding type etc.
    return ['length', 'width', 'thickness', 'color'];
  }

mixin expressProp(prop, val)
  case prop
    when 'length'
      | long de #[+value(val)]
    when 'width'
      | large de #[+value(val)]
    when 'color'
      | #[+value(val)]
    when 'thickness'
      | épais de #[+value(val)]
    default
      | TODO

mixin matterShape
  | je veux
  | #[+value(myShape)]
  | de
  | #[+value(myShape.matter)]

p
  | #[+matterShape] .
  eachz prop in getProps() with { mode: 'sentences', separator: '.' }
    | je veux que
    | #[+subjectVerb(myShape, {verb: 'être', tense: 'SUBJONCTIF_PRESENT'})]
    | #[+expressProp(prop, myShape[prop])]
```


Still you might prefer going towards something more fancy:
```pug
- 
  const myShape = {
    type: 'rectangle',
    length: '1 m', 
    width: '48 cm',
    thickness: '10 cm',
    color: 'rouge',
    matter: 'terre'
   };

mixin myShape_ref(obj, params)
  | #[+value(myShape.type, { det: 'INDEFINITE' })]
  - setRefGender(myShape, myShape.type);
- myShape.ref = myShape_ref;

mixin myShape_refexpr(obj, params)
  | #{getMFN(['il', 'elle'], myShape)}
- myShape.refexpr = myShape_refexpr;

-
  function getProps() {
    // could be dynamic, taking all props and excluding type etc.
    return ['length', 'width', 'thickness', 'color'];
  }

mixin express_length(val)
  | long de #[+value(val)]
mixin express_width(val)
  | large de #[+value(val)]
mixin express_color(val)
  | #[+value(val)]
mixin express_thickness(val)
  | épais de #[+value(val)]

mixin matterShape
  | je veux
  | #[+value(myShape)]
  | de
  | #[+value(myShape.matter)]

p
  | #[+matterShape] .
  eachz prop in getProps() with { mode: 'sentences', separator: '.' }
    | je veux que
    | #[+subjectVerb(myShape, {verb: 'être', tense: 'SUBJONCTIF_PRESENT'})]
    - pug_mixins['express_' + prop](myShape[prop])
```

**Comment by jeanvittor** [comment]
I see. Looks like `pug_mixins` allows to parametrize a mixin's name.
I haven't found it in pug's doc; and this seems to do the trick.

Thanks @ludans

**Comment by ludans** [comment]
thanks, I documented it, doc will be in the next version

**Comment by dddominikk** [comment]
> I see. Looks like `pug_mixins` allows to parametrize a mixin's name.
> I haven't found it in pug's doc; and this seems to do the trick.
> 
> Thanks @ludans

If you are super serious about this, I'd advise you start thinking about planning sentiments instead of sentences, as gimmicky as that sounds. You already have the vocabulary to pursue the answers you need, based on this thread title.

At the end of the day, however, you're going to have to get your hands dirty because it's going to be a long while before anyone starts addressing anyone's personalized NLG requirements IMO. Start from the end, what do you want written, no, _why_ do you want it written? Defining objects/classes describing your ideal nlg content is a good mental exercise, from my experience. Once you have those, you can start thinking about designing an actual data schema that would inform your interpolation decisions and whatnot.
