### ISSUE TITLE
[OTHER] How to throw an error if I write a wrong object field in a template?

### ISSUE THREAD

**Issue by radu1690** [RosaeNLG/rosaenlg#82]
Basically I have this object in my js file:
```
var person= {}  
person.name= "Rick"
```
Then I pass this object to RosaeNLG and let's say I make a mistake in my pug file and write something like:
```
|!{person.namee}
```
Can I throw an error somehow? Currently it prints an empty string.

Thanks in advance!

**Comment by ludans** [comment]
Hi @radu1690 

This seems to be the default behavior of Pug interpolation, when using `!{...}` and `#{...}`.

Typically, I favor the use of [value](https://rosaenlg.org/rosaenlg/3.0.0/mixins_ref/value.html) mixin which:
- allows formatting
- manages such errors

```pugjs
-
  var person= {}  
  person.name= "Rick"
| #[+value(person.namee)]
```
will produce an error: `InvalidArgumentError: first parameter of value is null or undefined on line 4`

**Comment by radu1690** [comment]
Awesome, I missed that page!

Is there also something similiar to use with If statements in templates? For example this should throw an error:
```
if person.namee == "Rick"
```

**Comment by ludans** [comment]
`if` statements are directly compiled in JavaScript. Pug (and RosaeNLG) do nothing special here.
`person.namee` is `undefined`, it is not invalid. I would say that in JavaScript it is valid to compare `undefined` with something else, here "Rick" - I don't think you can do anything about it?

**Comment by radu1690** [comment]
Thank you!

**Comment by dddominikk** [comment]
@radu1690 you should probably stick to the strictest === equality operator if errors are what you are after. This comparison table isn't complete but it covers the most common use cases, so should be helpful: 

![](https://i.stack.imgur.com/yISob.png)

Catching errors at chokepoints just enough to keep going (probably going toward a catastrophic failure months down the road) is what JS excels at hah, if you end up tinkering with the innards, try{}catch{}finally{} and .catch(err) are the two patterns I'd look into if I was you.
