### ISSUE TITLE
caractères spéciaux

### ISSUE THREAD

**Issue by houssem3107** [RosaeNLG/rosaenlg#83]
Hello,

when i produce RosaeNlg text , i have always problems with special chars ( é , è , à , ù , ....) that don't appear in the right form.

Is there maybe a RosaeNlg library to include in the pug code in order to solve the problem?

Thanks

**Comment by ludans** [comment]
This code:
```pugjs
| éùàç
```
produces `Éùàç`.

<img width="642" alt="example" src="https://user-images.githubusercontent.com/20767031/121368903-b4e39800-c93b-11eb-80ea-19abe29ed202.PNG">

Can you please precise what is the issue? Can you reproduce the error?

**Comment by houssem3107** [comment]
i have written pug code
![Capture d’écran 2021-06-09 161752](https://user-images.githubusercontent.com/77724372/121372073-4f44db00-c93e-11eb-806a-315dd4b5090f.png)

 that when i execute with the following
![image](https://user-images.githubusercontent.com/77724372/121372408-90d58600-c93e-11eb-867c-4c88c7670310.png)
the special chars don t appear in the correct form
![image](https://user-images.githubusercontent.com/77724372/121372576-b06cae80-c93e-11eb-8151-cf40f8582f3c.png)

**Comment by ludans** [comment]
Yes I see that.
I am pretty sure that this is due to encoding issues (not in RosaeNLG), it can be:
- in the `.pug` file: must be UTF-8
- in the terminal itself: to check that, instead on using `console.log`, write the text in a file and check it with VSCode

PS see below, I manage having a proper encoding in the output
![image](https://user-images.githubusercontent.com/20767031/121375864-591c0d80-c941-11eb-8e31-712b81320811.png)

**Comment by houssem3107** [comment]
I think there is a problem with the .pug file because i ve tried to write the text in a file and i ve tried with a diffrent terminal but the problem persists.

I don't really know where to add the UTF-8 encoding to correct the problem of the .pug file

**Comment by ludans** [comment]
In my screenshot, at the bottom on the right you can see "UTF-8". Check that you have UTF-8 there and if not, save with UTF-8 encoding. You might find help on the internet to do that.

**Comment by houssem3107** [comment]
okay thanks for the clarification
