### ISSUE TITLE
[OTHER] nopugmode.js file missing

### ISSUE THREAD

**Issue by henryjameslau** [RosaeNLG/rosaenlg#90]
In the documentation, it says there's some example of usage without templates in `noPugMode.js` but I can't seem to find that file.

**Comment by ludans** [comment]
file is here: https://github.com/RosaeNLG/rosaenlg/blob/master/packages/rosaenlg/test/test-rosaenlg/noPugMode.js
it's called `noPugMode.js`, but it looks like github is unable to find it using the search engine

**Comment by henryjameslau** [comment]
Thank you
