### ISSUE TITLE
[FEATURE] Override punctuation formatting

### ISSUE THREAD

**Issue by theojolliffe** [RosaeNLG/rosaenlg#91]
**Is your feature request related to a problem? Please describe.**
Rosae currently seems to add a space between a number and its percentage symbol. I think this may be a decision that adheres to some style guides but the organisation I'm publishing for requires percentages to be written without a space.

**Describe the solution you'd like**
Is there anyway to override such style decisions?

**Comment by ludans** [comment]
thanks @theojolliffe 

I understand and I agree - different organizations, different styles.

I would suggest to use number formatting feature: https://rosaenlg.org/rosaenlg/3.0.1/mixins_ref/value_numbers.html

```
| #[+value(0.365, {'FORMAT': '0.00%'})]
| #[+value(0.365, {'FORMAT': '0 %'})]
```

will output:
```36.50% 37 %```

**Comment by theojolliffe** [comment]
Thanks a lot for the help. And thanks for creating such a great NLP library!
