### ISSUE TITLE
[BUG] inconvenient spaces in tag name interpolation and attributes

### ISSUE THREAD

**Issue by MathiasWinckel** [RosaeNLG/rosaenlg#97]
**Describe the bug**
When using interpolation for a tag name, or simply adding attributes to a tag, it will generate extra spaces and a lot of a html/xml tools won't accept that.

**To Reproduce**
The following template:
```
- var tagName = "p"
#{tagName}(attr="value") test
```
generates
`< p attr= "value" > test </ p >`

**Expected behavior**
a clean formatted xml: "`<p attr="value">test</p>`"

**Context:**
 - RosaeNLG version: 3.0.0
 - Language: tested in EN/FR, but should be any
 - Packaging: nodejs, but reproducible in web version https://rosaenlg.org/rosaenlg/3.0.2/quickstart.html#_in_the_browser

**Additional context**

**Comment by MathiasWinckel** [comment]
I have a correction to submit.
Basically, in pug's code generator, to add an argument to avoid adding space in some case:
`bufferExpression: function (src, addSpaces=true) {`
and be able to avoid adding the `"¤"` symbol in the generated code when editing the `this.lastBuffered`

Already run the tests, seems good to go.

**Comment by ludans** [comment]
if the tests run, it is a good sign!
**can you please add a regression test for this specific case?** 
I'll be happy to review your PR as it seems almost ready :)

**Comment by MathiasWinckel** [comment]
I just added a commit with a non regression test

**Comment by ludans** [comment]
published in 3.0.3
