### ISSUE TITLE
[BUG?] Macao vs Macau in english

### ISSUE THREAD

**Issue by MathiasWinckel** [RosaeNLG/rosaenlg#99]
**Describe the bug**
In several cases, the countries lib will display "Macau" when "Macao" could be a valid option.

**To Reproduce**
any use of the "Macau" country name in an english text

**Expected behavior**
For what I understand from different articles on Macau/Macao: 
"Macau" would be the Portuguese spelling of the name, reformed a century ago, but a lot of other languages may keep using "Macao".
I would find the "Macao" version to be a better option for texts in English, since it's already spelled like that in its official name _"Macao Special Administrative Region of the People's Republic of China"_ it may seem more coherent.

**Context:**
 - RosaeNLG version: [3.0.3]
 - Language: [en_US]
 - Packaging: [node.js]

**Additional context**

**Comment by ludans** [comment]
Some info:
- is in `rosaenlg-country` module
- it relies on `world-countries` external lib

In English, it uses `name.common` (see in `rosaenlg\node_modules\world-countries\dist\countries.json`)

Here it is "Macau". "Macao" is in `altSpellings` field.
Wikipedia says: "Macau or Macao...".

I cannot say what it should be, but `world-countries` is a reference.

It is common to have some styling overrides per project.

Suggestion for this case:
- ask for the change in `world-countries` github https://github.com/mledoze/countries
- override locally in your project

**Comment by ludans** [comment]
@MathiasWinckel are you willing to make the change? Otherwise I shall close the ticket.
